name: Teste do GitHub Actions

on:
  push:
    branches:
      - main  # ajuste para a branch que deseja acionar o fluxo de trabalho

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # ajuste para a versão do Python que deseja utilizar

      - name: Install dependencies
        run: pip install feedparser

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar testes
        run: python atualiza.py
